# Generated by Django 2.1.5 on 2020-01-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('assigned_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('assignee_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.Portfolio')),
            ],
        ),
    ]
