# Generated by Django 2.1.5 on 2020-01-06 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20200106_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='store_name',
            field=models.CharField(default=datetime.datetime(2020, 1, 6, 19, 4, 52, 134443, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
